### ISSUE TITLE
ccRegistry.pas is missing from the repo

### ISSUE THREAD

**Issue by jasoft** [GabrielOnDelphi/Delphi-LightSaber#1]
I tried to build the package and found the use of ccRegistry in ccAppData.pas is missing.

**Comment by GabrielOnDelphi** [comment]
> I tried to build the package and found the use of ccRegistry in ccAppData.pas is missing.

Hi. There was an update yesterday. Now ccRegistry is named cmRegistry.

**Comment by GabrielOnDelphi** [comment]
cc - is cubic **core**
cm - is cubic **comon**
So registry is not part of the Core package anymore. Was moved to the Common package.

**Comment by GabrielOnDelphi** [comment]
Hi. Can we close the issue now?
